api_root_path: /
auto_reload: false
aws_config_ini: null
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_print_logs: false
docs_url: /docs
host: 127.0.0.1
log_level: info
openapi_url: /openapi.json
port: 8080
service_name: metadata_transpiler_service
workers: 1
