api_root_path: /
auto_reload: true
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
docs_url: /docs
host: 127.0.0.1
log_level: info
mapping_url: /data/mapping.json
openapi_url: /openapi.json
port: 8080
schema_version: 0.7.0
service_name: metadata_transpiler_service
workers: 1
