#!/bin/bash
# install service in dev container

cd /workspace


# install in edit mode
# use-feature way of installing packages
# install with testing dependencies
pip install \
    --use-feature=2020-resolver \
    -e \
    ".[all]"

# install pre-commit hooks to git:
pre-commit install
